name: docker push
on: workflow_dispatch
    
    
jobs:
  release:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: evermind/openjdk-service

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{github.workspace}}/Dockerfile.17-slim
          tags: evermind/openjdk-service:17-slim
          push: true
